Module2 task1
htmlacademy-javascript/1969965-kekstagram-28 pull request #2
Opened 2023-02-21 22:52 UTC by JulianaAstra

Алёна, здравствуйте! Первые три задачи решила до лайва, во время лайва немножко улучшила, а вот четвёртую задачу, хоть и смотрела лайв, решила сама, не стала копировать чужое. Но, по мне, решение вышло очень топорным и "страшным". Пыталась рефакторить, но что-то ничего не пришло в голову.

2023-02-22 04:05 UTC, Safyann requested changes
Хорошо, но 3 функцию надо доработать для выполнения всех условий, посомтри в сторону на replace(/\D/g, ''), то есть удалить все кроме цифр из строуи и сэтим можно поработать, по 4 функции про if else чуть замудрила но главное работает, как чуть упростить написала

2023-02-22 04:05 UTC, Safyann commented on js/functions.js
> +  } else if (Array.from(phrase.replaceAll('.', '')).every((element) => isNaN(element))) {
сломается на примере getNumberFromString('1 кефир, 0.5 батона')
посмотри в сторону phrase.replace(/\D/g, '')

2023-02-22 04:05 UTC, Safyann commented on js/functions.js
> +  if (string.length < minLength) {
тут проще наоборот сделать, то есть сначала проверить и вернуть строку, меньше вложенности будет
if (string.length >= minLength) { return string };
...

2023-02-22 04:05 UTC, Safyann commented on js/functions.js
> +    } else if (padChar.length === lengthNeeded) {
если есть return то не обязательно писать else if

2023-02-22 04:05 UTC, Safyann commented on js/functions.js
> +    } else if (padChar.length < lengthNeeded) {
если есть return то не обязательно писать else if

То есть функция примет вид

    if (string.length >= minLength) {
      return ...
    }
     ...
    if (padChar.length > lengthNeeded) {
     return ...
    }
    if (padChar.length === lengthNeeded) {
      return ...
    }
    if (padChar.length < lengthNeeded) {
      ...
      if (lengthNeeded % padChar.length !== 0) {
        return ...
      }
      return ...
    }

2023-02-22 13:19 UTC, JulianaAstra commented on js/functions.js
> +  } else if (Array.from(phrase.replaceAll('.', '')).every((element) => isNaN(element))) {
Я, к сожалению, не знаю, что такое (/\D/g, '').

2023-02-22 13:54 UTC, JulianaAstra commented
- Исправила третью задачу, оказалось, что когда копировала кусок кода из первого условия, не заметила, что там нужно было заменять не точку на пустую строку, а пробел. Теперь пример с хлебом работает. Я правильно понимаю, что в будущем такую операцию будет проще сделать с помощью регулярных выражений? 
- Поправила замечания по остальным задачам.

2023-02-23 11:27 UTC, Safyann approved these changes
про регулярки, да проще потом с ними /\D/g как раз ищет нецифровые символы и '' через repalce удалям все буквы и точки

2023-02-23 11:27 UTC, merged