5.14 Модуляция
htmlacademy-javascript/1969965-kekstagram-28 pull request #4
Opened 2023-03-03 14:33 UTC by JulianaAstra

Алёна, здравствуйте! Раздробила код максимально мелко, возможно, перебор))
У меня одна проблема: не получилось через импорт в файле create-pictures.js сделать так, чтобы генерировались подписи к фотографиям. Возможно, я не до конца понимаю механизм, как это работает... Я указала в комментариях к коду место, где не получается.

2023-03-04 06:59 UTC, Safyann approved these changes
Огонь, но чтобы прям идеально было можно еще

1. вынести все констаны тоже в отдельный файл, можно так и назвать constant
2. и еще можно распихать все по папкам тип есть вспомогательные функции изх обычно называют helpers или tools и туда скидать все функции аля генерация чисел или  все get функции, чтобы просто большой список файлов в одной папке не был, так как функции еще будет добавляться

2023-03-04 06:59 UTC, Safyann commented on js/get-random-name.js
> +const SURNAMES = [
все константы тоже бы куда-нибудь вынести в отдельный файл и делать импорт где надо

2023-03-04 07:46 UTC, Safyann requested changes

2023-03-04 07:46 UTC, Safyann commented on js/main.js
> +newPictures();
это не функция, будет ошибка. Можно просто оставить getPictures();

2023-03-04 07:46 UTC, Safyann commented on js/generate-comment-id.js
> +const generateCommentId = () => createSerialNumberGenerator();
уже функция в функции, тут надо оставить
`const generateCommentId =  createSerialNumberGenerator();`

2023-03-04 07:46 UTC, Safyann commented on js/create-pictures.js
> +import { getPhotoDescription, PHOTO_DESCRIPTIONS } from './get-photo-description.js'; // здесь должна одна быть функция getPhotoDescription
тут оставим только импорт функции

2023-03-04 07:46 UTC, Safyann commented on js/create-pictures.js
> +    description: PHOTO_DESCRIPTIONS[getPhotoDescription()], // вот здесь не получилось через импорт, вся конструкция перестаёт работать
тут только вызов getPhotoDescription()

2023-03-04 07:46 UTC, Safyann commented on js/get-photo-description.js
> +
можно добавить const generateDescriptionIndex = createSerialNumberGenerator();
что бы генерировать индекс для массива

2023-03-04 07:46 UTC, Safyann commented on js/get-photo-description.js
> +const getPhotoDescription = createSerialNumberGenerator(); // если делать условно: const getPhoto = PHOTO_DESCRIPTIONS[getPhotoDescription()], то в create-pictures.js он уже не рабоатет
const getPhotoDescription = () => PHOTO_DESCRIPTIONS[generateDescriptionIndex() - 1];

2023-03-06 12:38 UTC, JulianaAstra commented
Исправила ошибки, сделала файл с константами и папку для вспомогательных функций. Поняла, в чём была ошибка с описаниями фотографий: я присваивала переменной результат функции, а нужно было создать еще одну функцию на основе первой, поэтому она и не вызывалась в конструкторе. Спасибо за проверку!

2023-03-06 13:33 UTC, Safyann approved these changes

2023-03-06 13:33 UTC, merged